import ExperiencePage from "@/components/pages/experience/ExperiencePage";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Portfolio Project | Contact",
  description: "Generated by Portfolio Project Contact page",
};
const Experience = () => {
  return (
    <div>
      <ExperiencePage />
    </div>
  );
};

export default Experience;
