import AboutPage from "@/components/pages/about/AboutPage";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Portfolio Project | About",
  description: "Generated by Portfolio Project About page",
};
const About = () => {
  return (
    <div>
      <p>about oages</p>
      <AboutPage />
    </div>
  );
};

export default About;
