import BlogsPage from "@/components/pages/blogs/BlogsPage";
import Contact from "@/components/pages/contact/ContactPage";
import EducationPage from "@/components/pages/education/EducationPage";
import Experience from "@/components/pages/experience/ExperiencePage";
import Hero from "@/components/pages/home/Hero";
import ProjectsPage from "@/components/pages/projects/ProjectsPage";
import ServicesPage from "@/components/pages/services/ServicesPage";
import Skills from "@/components/pages/skills/SkillsPage";
import ParticleBackground from "@/components/partailBackground/PartailBackground";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Portfolio Project | Home",
  description: "Generated by Portfolio Project Home page",
};

const HomePage = () => {
  return (
    <div className="min-h-screen">
      <ParticleBackground />
      <Hero />
      <Experience />
      <Skills />
      <ProjectsPage />
      <ServicesPage />
      <EducationPage />
      <BlogsPage />
      <Contact />
    </div>
  );
};

export default HomePage;
