import EducationPage from "@/components/pages/education/EducationPage";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Portfolio Project | CEducation",
  description: "Generated by Portfolio Project Education page",
};
const Education = () => {
  return (
    <div>
      <EducationPage />
    </div>
  );
};

export default Education;
