import ServicesPage from "@/components/pages/services/ServicesPage";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Portfolio Project | Services",
  description: "Generated by Portfolio Project Services page",
};
const Services = () => {
  return (
    <div>
      <ServicesPage />
    </div>
  );
};

export default Services;
