import SkillsPage from "@/components/pages/skills/SkillsPage";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Portfolio Project | Skills",
  description: "Generated by Portfolio Project Skills page",
};
const Skills = () => {
  return (
    <div>
      <SkillsPage />
    </div>
  );
};

export default Skills;
