import ContactPage from "@/components/pages/contact/ContactPage";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Portfolio Project | Contact",
  description: "Generated by Portfolio Project Contact page",
};
const Contact = () => {
  return (
    <div>
      <ContactPage />
    </div>
  );
};

export default Contact;
