import BlogsPage from "@/components/pages/blogs/BlogsPage";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Portfolio Project | About",
  description: "Generated by streetGrub Blogs page",
};
const Blogs = () => {
  return (
    <div className="container mx-auto pt-8 md:px-6 px-2">
      <p>Blog PAGE ARE HERE</p>
      <BlogsPage />
    </div>
  );
};

export default Blogs;
