import LoginForm from "@/components/pages/login/LoginForm";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Portfolio Project | Login",
  description: "Generated by Portfolio Project login page",
};

const LoginPage = () => {
  return <LoginForm />;
};

export default LoginPage;
